# Generated by Django 5.1.5 on 2025-02-06 13:58

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_options_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=models.PROTECT, related_name='items', to='store.Order'),
        ),
    ]
